#!/usr/bin/env sh

source "$HOME/.config/colors.sh"

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# sketchybar height
yabai -m config external_bar all:38:0

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# new window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

# -- mouse settings --

# center mouse on window with focus
yabai -m config mouse_follows_focus on

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap

yabai -m config window_shadow float
# yabai -m config window_opacity on
# yabai -m config normal_window_opacity 0.95

yabai -m config insert_feedback_color $COLOR_RED

# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
borders active_color=$COLOR_WM_ACCENT_BRIGHT inactive_color=$COLOR_WM_ACCENT width=4 &

yabai -m rule --add subrole="^(AXDialog|AXSystemDialog|AXSheet)$" manage=off
yabai -m rule --add role="^AXPopUpButton$" manage=off
yabai -m rule --add title="^(Preferences|Settings|About).*" manage=off

# ENABLE specific apps
yabai -m rule --add app="^BlueStacks$" title="^BlueStacks Air$" manage=on
